### ISSUE TITLE
laravel配置了这个socket，连接不上，是配置的不对？

### ISSUE THREAD

**Issue by anyforever** [lyuangg/umyproxy#1]
host/port去掉了也不行

**Comment by lyuangg** [comment]
用的 laravel 版本是多少，有报错日志吗

**Comment by anyforever** [comment]
PHP 8.1.10 LARAVEL 9.38.0 

.env
```
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=forge
DB_USERNAME=root
DB_PASSWORD=
DB_PREFIX=
DB_SOCKET=/tmp/umyproxy.socket

```

**Comment by lyuangg** [comment]
> ▶ php artisan scout:import "App\Models\Article" Imported [App\Models\Article] models up to ID: 35 All [App\Models\Article] records have been imported. 导入成功，页面搜索的时候，提示下面的错误
> 
> MeiliSearch \ Exceptions \ ApiException PHP 8.1.10 LARAVEL 9.38.0 Index `articles` not found. MeiliSearch\Exceptions\ApiException(code: 404): Index `articles` not found. at /usr/local/var/www/forge/vendor/meilisearch/meilisearch-php/src/Http/Client.php:193)
> 
> .env
> 
> ```
> DB_CONNECTION=mysql
> DB_HOST=127.0.0.1
> DB_PORT=3306
> DB_DATABASE=forge
> DB_USERNAME=root
> DB_PASSWORD=
> DB_PREFIX=
> DB_SOCKET=/tmp/umyproxy.socket
> 
> SCOUT_DRIVER=meilisearch
> MEILISEARCH_HOST=http://127.0.0.1:7700
> #MEILISEARCH_KEY=masterKey
> ```

你这个报错跟访问数据库应该是没有关系的。

**Comment by anyforever** [comment]
哎呀，不好意思，发错了，正好在配置meilisearch搜索引擎，错发了那个的错误
连接mysql代理这个，没有报错。就是访问有没有响应，直到nginx响应504 Gateway Time-out，如果直连mysql就正常能读出来。

**Comment by lyuangg** [comment]
> 

mysql 版本是多少，我搞个环境测一下

**Comment by lyuangg** [comment]
@anyforever 有 bug ，修复了一下

**Comment by anyforever** [comment]
> 

 试了，好了。3Q
