### ISSUE TITLE
可以在生产环境中使用了吗？

### ISSUE THREAD

**Issue by dux-web** [lyuangg/umyproxy#2]

**Comment by lyuangg** [comment]
建议测试后使用

**Comment by lyuangg** [comment]
@duxphp  写了一个包  https://github.com/lyuangg/laravel-umyproxy 方便在 laravel 项目中使用

**Comment by dux-web** [comment]
测试过了 没什么问题  并发量600 稳定运行了好多天

**Comment by lyuangg** [comment]
> 测试过了 没什么问题 并发量600 稳定运行了好多天

可以试一下最新的代码，之前的代码在插入的时候会卡住

**Comment by dux-web** [comment]
> 

有个权限的问题 麻烦更新下
